apiVersion: v1
kind: Service
metadata:
  name: service-web-app-color
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30010
  selector:
    name: pod-simple-webapp-color
