apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - image: alpine:3.13.5
      name: alpine
      command: ["/bin/sh","-c"]
      args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
      volumeMounts:
       - mountPath: /opt
         name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
          claimName: myclaim

