--- 
apiVersion: v1
kind: Pod
metadata: 
  name: pod-affinity
spec: 
  affinity: 
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms: 
          - 
            matchExpressions: 
              - 
                key: size
                operator: NotIn
                values: 
                  - Small
                  - Large
  containers: 
    - 
      image: redis
      name: redis

